
Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-8m57z[0m
{"level":"warn","ts":1583480360.4410863,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1583480360.441402,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-bntcq[0m
{"level":"warn","ts":1583480361.5446112,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1583480361.591004,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-testrepo-master-rele-nslcg-bnnz6[0m
{"level":"warn","ts":1583480368.7729924,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1583480371.3680084,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/testRepo.git @ v0.0.2 in path /workspace/source"}

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:356496e4d4493f2cb841a5d7e63df0095589db79
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/06 07:39:34 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/06 07:39:37 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0003] Executing 3 build triggers                   
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0004] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] Skipping unpacking as no commands require it. 
[36mINFO[0m[0004] Taking snapshot of full filesystem...        
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Found cached layer, extracting to filesystem 
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] COPY . /usr/src/app                          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt .                      
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] ENV PORT 8080                                
[36mINFO[0m[0004] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0004] EXPOSE 8080                                  
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0004] ENTRYPOINT ["python"]                        
[36mINFO[0m[0004] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0004] CMD ["app.py"]                               
[36mINFO[0m[0004] No files changed in this command, skipping snapshotting. 
2020/03/06 07:39:39 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/06 07:39:39 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/06 07:39:39 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/06 07:39:39 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/06 07:39:39 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/06 07:39:39 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/06 07:39:39 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/06 07:39:39 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/06 07:39:39 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/06 07:39:40 pushed blob: sha256:5e8ee57e33249ecb62b819983c2652ae241b3511c04bd7f3fd7cc1aa247470c8
2020/03/06 07:39:40 pushed blob: sha256:98c5dc4be07e91cf323ad03fba3a4775c6506ac97fdb94669f280cbbfa96a31d
2020/03/06 07:39:40 pushed blob: sha256:0cf2f10cec8b7c982660e7ec47de26ab84b2a2143788b414b43186ddedd3ab40
2020/03/06 07:39:40 pushed blob: sha256:9e344efea2cd9e4a879caa50bebd1927d11920347ed4b6d87ef3c0fd047ebf9b
2020/03/06 07:39:40 pushed blob: sha256:8086f5ac4927ff9911f280747dbaf30da46430aa8fb773212b09b3410abae633
2020/03/06 07:39:40 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/testrepo:0.0.2: digest: sha256:cef8908b556b883b53d93cc05b0abec1e619569e154137762a8c55930b851542 size: 2385

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-testrepo-master-rele-nslcg-5[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
/bin/sh: line 0: cd: /workspace/source/charts/testRepo: No such file or directory
[31m
Pipeline failed on stage 'from-build-pack' : container 'step-promote-changelog'. The execution of the pipeline has stopped.[0m
